(PE-36810) Stop using dynamic tmp directory for batch script
puppetlabs/bolt-vanagon pull request #199
Opened 2023-09-25 23:09 UTC by donoghuc

This commit removes the intermediate script constructed for installation from being written to the %TEMP% directory. Intead it is written to the same directory the script is being run from. This ensures users must be able to write to the directory this script is being run from (for example C:\windows\system32 instead of %TEMP%).

2023-09-26 20:32 UTC, donoghuc commented
This is installed on `wishful-novelty.delivery.puppetlabs.net` and logs are available as shown:

```
C:\cygwin64\home\Administrator>cmd /c start /w msiexec /qn /i puppet-bolt-3.27.2.15.g0e30aca-x64.msi /L*V installlog.txt
cmd /c start /w msiexec /qn /i puppet-bolt-3.27.2.15.g0e30aca-x64.msi /L*V installlog.txt
```

2023-09-27 16:43 UTC, mcdonaldseanp requested changes
Oh I didn't realize I had a pending review! One concern

2023-09-28 23:24 UTC, donoghuc commented on resources/windows/wix/tarball.vbs
> +  Dim tempFilePath : tempFilePath = fso.GetTempName()
Cool, updated. I had some trouble ensuring there was a subdirectory under `C\Windows\Installer`. I think adding the files there and then cleaning them up should be good.

2023-09-29 17:16 UTC, mcdonaldseanp approved these changes

2023-09-29 17:17 UTC, merged