Update platform support (x86_64)
puppetlabs/bolt-vanagon pull request #208
Opened 2024-10-29 17:58 UTC by alex501212

In this pr I have removed any EOL OSes and added new ones

Removed platforms:
debian-9-amd64
debian-10-amd64
el-6-x86_64
fedora-36-x86_64
windows-2012r2-x64

Added platforms:
debian-12-amd64
fedora-40-x86_64
osx-13-x86_64
osx-14-x86_64
ubuntu-24.04-amd64
windows-2019-x64

2024-10-29 18:19 UTC, donoghuc commented
Thanks, can you please link a corresponding cjc PR. That will help reviewer understand the addition/deletions.

2024-10-30 10:03 UTC, alex501212 commented
> Thanks, can you please link a corresponding cjc PR. That will help reviewer understand the addition/deletions.

updated now

2024-10-30 15:55 UTC, donoghuc requested changes
I think the strategy for windows is to build for the oldest platform possible then test on the newer ones. That is one of the reasons I encouraged raising the cjc PR. You can see there we are building for `windows-2012r2-x64` then testing on `windows2019`. I think we should continue that pattern until we finally need to drop `2012`. At that time we should replace it with the next oldest, widely available windows vm.

2024-10-30 20:02 UTC, donoghuc approved these changes

2024-10-30 20:04 UTC, merged